[build]
  command = "npm run build"
  publish = "public"
  functions = "functions-dist"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "functions-dist"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"